@Api_HostAddress = http://localhost:5019/api/v1

POST {{Api_HostAddress}}/organisation/register
Content-Type: application/json
Timezone-Offset: 330

{
    "email": "elsonjoseofficial@gmail.com",
    "password": "P@ssword123",
    "name": "TeamSync",
    "isDomainCheckEnabled": false
}

###

POST {{Api_HostAddress}}/auth/register
Content-Type: application/json

{
    "firstName":"firtName",
    "lastName":"lastName",
    "email": "string",
    "password": "string"
}

###
