@Api_HostAddress = http://localhost:5019/api/v1

POST {{Api_HostAddress}}/auth/login
Content-Type: application/json

{
    "email": "string",
    "password": "string"
}

###

POST {{Api_HostAddress}}/auth/register
Content-Type: application/json

{
    "firstName":"firtName",
    "lastName":"lastName",
    "email": "string",
    "password": "string"
}

###
